<a href="https://colab.research.google.com/github/Saptasindhu07/Logistic-Regression/blob/main/Multiclass_Classification_using_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:

data=pd.read_csv('/content/drive/MyDrive/ML Datasets/student_performance_dataset.csv')
data.head()

study_hours  attendance_percentage  previous_test_score performance
0        6.375                 74.234               67.892         Low
1       14.766                 92.345               85.123        High
2        9.234                 68.567               55.678      Medium
3        3.456                 59.123               48.901         Low
4       17.891                 97.456               92.345        High

In [ ]:
encoding_map = {'Low': 0, 'Medium': 1, 'High': 2}
data['performance'] = data['performance'].replace(encoding_map)
data

<ipython-input-3-3bdfd9d3c5be>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['performance'] = data['performance'].replace(encoding_map)


study_hours  attendance_percentage  previous_test_score  performance
0           6.375                 74.234               67.892            0
1          14.766                 92.345               85.123            2
2           9.234                 68.567               55.678            1
3           3.456                 59.123               48.901            0
4          17.891                 97.456               92.345            2
...           ...                    ...                  ...          ...
1136        7.456                 99.901               99.901            1
1137       17.456                 99.901               99.901            2
1138        4.567                 99.901               99.901            0
1139       12.901                 99.901               99.901            2
1140        9.567                 99.901               99.901            1

[1141 rows x 4 columns]

In [ ]:
X=data.iloc[:,0:3]
X.head()

study_hours  attendance_percentage  previous_test_score
0        6.375                 74.234               67.892
1       14.766                 92.345               85.123
2        9.234                 68.567               55.678
3        3.456                 59.123               48.901
4       17.891                 97.456               92.345

In [ ]:
y=data.iloc[:,3]
y.head()

0    0
1    2
2    1
3    0
4    2
Name: performance, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

# **LOGISTIC REGRESSION FOR MULTICLASS CLASSIFICATION**

In [ ]:
logistic=LogisticRegression(multi_class='ovr')
logistic.fit(X_train,y_train)


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [ ]:
y_pred=logistic.predict(X_test)
y_pred

array([2, 2, 1, 0, 2, 2, 1, 2, 0, 2, 1, 1, 1, 2, 2, 2, 1, 2, 0, 1, 2, 2,
       1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 2, 0,
       1, 2, 1, 1, 0, 2, 1, 2, 2, 0, 1, 2, 1, 0, 2, 1, 2, 2, 0, 0, 0, 1,
       2, 2, 0, 0, 1, 1, 1, 0, 2, 2, 0, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2,
       1, 0, 1, 2, 2, 0, 1, 1, 2, 0, 0, 2, 2, 2, 0, 1, 2, 1, 0, 1, 0, 2,
       2, 0, 1, 2, 1, 2, 2, 2, 1, 0, 2, 1, 0, 2, 0, 1, 2, 2, 1, 1, 2, 1,
       1, 1, 2, 0, 2, 0, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 0, 1, 1, 2, 2, 1,
       2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 2, 0, 1, 0, 1, 0, 1,
       1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 0, 0, 1, 2, 1, 1, 2, 0, 1, 2, 2, 0,
       1, 1, 1, 2, 0, 2, 2, 1, 0, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 0, 2, 0,
       2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1,
       0, 2, 0, 0, 2, 2, 1, 0, 1, 1, 0, 2, 1, 1, 0, 2, 1, 1, 2, 1, 0, 1,
       2, 2, 1, 0, 0, 1, 1, 1, 2, 2, 1, 2, 1, 0, 2, 0, 0, 1, 0, 1, 2, 1])

In [ ]:
confusion_matrix(y_pred,y_test)

array([[ 64,   1,   0],
       [  0, 110,   0],
       [  0,   0, 111]])

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        65
           1       0.99      1.00      1.00       110
           2       1.00      1.00      1.00       111

    accuracy                           1.00       286
   macro avg       1.00      0.99      1.00       286
weighted avg       1.00      1.00      1.00       286



# **TIME FOR SOME HYPERPARAMETER TUNING**

In [ ]:
penalty=['l2','elasticnet']
cValues=[100,10,1.0,0.1,0.01,0.001,1000]
solver=['lbfgs','liblinear','sag','saga']
params=dict(penalty=penalty,C=cValues,solver=solver)
params

{'penalty': ['l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01, 0.001, 1000],
 'solver': ['lbfgs', 'liblinear', 'sag', 'saga']}

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

In [ ]:
CV= StratifiedKFold()

In [ ]:
grid= GridSearchCV(estimator=logistic,param_grid=params,scoring='recall',cv=CV,n_jobs=-1)
grid


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(multi_class='ovr'), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01, 0.001, 1000],
                         'penalty': ['l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'sag', 'saga']},
             scoring='recall')

In [ ]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
140 fits failed out of a total of 280.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solv

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(multi_class='ovr'), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01, 0.001, 1000],
                         'penalty': ['l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'sag', 'saga']},
             scoring='recall')

In [ ]:
y_test=grid.predict(X_test)
y_test

array([2, 2, 1, 0, 2, 2, 1, 2, 0, 2, 1, 1, 1, 2, 2, 2, 1, 2, 0, 1, 2, 2,
       1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 2, 0,
       1, 2, 1, 1, 0, 2, 1, 2, 2, 0, 1, 2, 1, 0, 2, 1, 2, 2, 0, 0, 0, 1,
       2, 2, 0, 0, 1, 1, 1, 0, 2, 2, 0, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2,
       1, 0, 1, 2, 2, 0, 1, 1, 2, 0, 0, 2, 2, 2, 0, 1, 2, 1, 0, 1, 0, 2,
       2, 0, 1, 2, 1, 2, 2, 2, 1, 0, 2, 1, 0, 2, 0, 1, 2, 2, 1, 1, 2, 1,
       1, 1, 2, 0, 2, 0, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 0, 1, 1, 2, 2, 1,
       2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 2, 0, 1, 0, 1, 0, 1,
       1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 0, 0, 1, 2, 1, 1, 2, 0, 1, 2, 2, 0,
       1, 1, 1, 2, 0, 2, 2, 1, 0, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 0, 2, 0,
       2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1,
       0, 2, 0, 0, 2, 2, 1, 0, 1, 1, 0, 2, 1, 1, 0, 2, 1, 1, 2, 1, 0, 1,
       2, 2, 1, 0, 0, 1, 1, 1, 2, 2, 1, 2, 1, 0, 2, 0, 0, 1, 0, 1, 2, 1])

In [ ]:
confusion_matrix(y_pred,y_test)

array([[ 65,   0,   0],
       [  0, 110,   0],
       [  0,   0, 111]])